/* eslint-disable @typescript-eslint/no-duplicate-enum-values */
export enum ErrorCase {
  NOT_FOUND = 404,
  VALIDATION_FAILED = 400,
  UNAUTHORIZED = 401,
  INTERNAL = 500,
  ALREADY_SUBMITTED = 400,
  CANNOT_CHANGE_TEMPLATE_TYPE = 400,
  CANNOT_SUBMIT = 400,
  CANNOT_APPROVE = 400,
  FEATURE_DISABLED = 403,
  CONFLICT = 409,
  TEMPLATE_IN_USE = 400,
  ROUTING_CONFIG_TEMPLATES_NOT_FOUND = 400,
}
