name: "Node modules cache + setup (pnpm)"
description: "Setup Node, cache pnpm store via setup-node, prefetch tarballs, and link node_modules from the store"
inputs:
  node_version:
    description: "Node.js version"
    required: true
  cache_lock_path:
    description: "Path(s) to pnpm-lock.yaml for cache key"
    required: false
    default: "**/pnpm-lock.yaml"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: "Use Node.js"
      uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node_version }}"
        cache: "pnpm"
        cache-dependency-path: "${{ inputs.cache_lock_path }}"

    - name: "Prefetch deps to pnpm store"
      shell: bash
      run: pnpm fetch --prefer-offline -r

    - name: "Link node_modules from store"
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline -r
