export type ExampleRecipient = {
  id: string;
  name: string;
  data: Record<string, string>;
};

export const SHORT_EXAMPLE_RECIPIENTS: ExampleRecipient[] = [
  {
    id: 'short-1',
    name: 'Jo Bloggs',
    data: {
      nhsNumber: '9728543751',
      firstName: 'Jo',
      lastName: 'Bloggs',
      fullName: 'Jo Bloggs',
      middleNames: '',
      namePrefix: '',
      nameSuffix: '',
      address_line_1: 'Jo Bloggs',
      address_line_2: '1 High Street',
      address_line_3: 'Leeds',
      address_line_4: 'West Yorkshire',
      address_line_5: 'LS1 1AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-2',
    name: 'Mr John Smith',
    data: {
      nhsNumber: '9728543752',
      firstName: 'John',
      lastName: 'Smith',
      fullName: 'Mr John Smith',
      middleNames: '',
      namePrefix: 'Mr',
      nameSuffix: '',
      address_line_1: 'Mr John Smith',
      address_line_2: '2 Oak Road',
      address_line_3: 'London',
      address_line_4: 'SW1A 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-3',
    name: 'Ms Sarah Jones',
    data: {
      nhsNumber: '9728543753',
      firstName: 'Sarah',
      lastName: 'Jones',
      fullName: 'Ms Sarah Jones',
      middleNames: '',
      namePrefix: 'Ms',
      nameSuffix: '',
      address_line_1: 'Ms Sarah Jones',
      address_line_2: '3 Park Lane',
      address_line_3: 'Manchester',
      address_line_4: 'M1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-4',
    name: 'Dr Li Wei',
    data: {
      nhsNumber: '9728543754',
      firstName: 'Li',
      lastName: 'Wei',
      fullName: 'Dr Li Wei',
      middleNames: '',
      namePrefix: 'Dr',
      nameSuffix: '',
      address_line_1: 'Dr Li Wei',
      address_line_2: '4 Queen Street',
      address_line_3: 'Birmingham',
      address_line_4: 'B1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-5',
    name: 'Mrs Mary Brown',
    data: {
      nhsNumber: '9728543755',
      firstName: 'Mary',
      lastName: 'Brown',
      fullName: 'Mrs Mary Brown',
      middleNames: '',
      namePrefix: 'Mrs',
      nameSuffix: '',
      address_line_1: 'Mrs Mary Brown',
      address_line_2: '5 King Road',
      address_line_3: 'Bristol',
      address_line_4: 'BS1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-6',
    name: 'Rev Mia Dao',
    data: {
      nhsNumber: '9728543756',
      firstName: 'Mia',
      lastName: 'Dao',
      fullName: 'Rev Mia Dao',
      middleNames: '',
      namePrefix: 'Rev',
      nameSuffix: '',
      address_line_1: 'Rev Mia Dao',
      address_line_2: '6 Church Lane',
      address_line_3: 'Oxford',
      address_line_4: 'OX1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-7',
    name: 'Miss Lucy Taylor',
    data: {
      nhsNumber: '9728543757',
      firstName: 'Lucy',
      lastName: 'Taylor',
      fullName: 'Miss Lucy Taylor',
      middleNames: '',
      namePrefix: 'Miss',
      nameSuffix: '',
      address_line_1: 'Miss Lucy Taylor',
      address_line_2: '7 Mill Road',
      address_line_3: 'Cambridge',
      address_line_4: 'CB1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-8',
    name: 'Mx Alex Chen',
    data: {
      nhsNumber: '9728543758',
      firstName: 'Alex',
      lastName: 'Chen',
      fullName: 'Mx Alex Chen',
      middleNames: '',
      namePrefix: 'Mx',
      nameSuffix: '',
      address_line_1: 'Mx Alex Chen',
      address_line_2: '8 Bridge Street',
      address_line_3: 'York',
      address_line_4: 'YO1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-9',
    name: 'Prof Ola Fye',
    data: {
      nhsNumber: '9728543759',
      firstName: 'Ola',
      lastName: 'Fye',
      fullName: 'Prof Ola Fye',
      middleNames: '',
      namePrefix: 'Prof',
      nameSuffix: '',
      address_line_1: 'Prof Ola Fye',
      address_line_2: '9 Castle Road',
      address_line_3: 'Durham',
      address_line_4: 'DH1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-10',
    name: 'Dr James Patel',
    data: {
      nhsNumber: '9728543760',
      firstName: 'James',
      lastName: 'Patel',
      fullName: 'Dr James Patel',
      middleNames: '',
      namePrefix: 'Dr',
      nameSuffix: '',
      address_line_1: 'Dr James Patel',
      address_line_2: '10 Abbey Lane',
      address_line_3: 'Bath',
      address_line_4: 'BA1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'short-11',
    name: 'Ms Claire Davies',
    data: {
      nhsNumber: '9728543761',
      firstName: 'Claire',
      lastName: 'Davies',
      fullName: 'Ms Claire Davies',
      middleNames: '',
      namePrefix: 'Ms',
      nameSuffix: '',
      address_line_1: 'Ms Claire Davies',
      address_line_2: '11 Harbour View',
      address_line_3: 'Plymouth',
      address_line_4: 'PL1 1AA',
      address_line_5: '',
      address_line_6: '',
      address_line_7: '',
    },
  },
];

export const LONG_EXAMPLE_RECIPIENTS: ExampleRecipient[] = [
  {
    id: 'long-1',
    name: 'Mr Michael James Richardson-Clarke',
    data: {
      nhsNumber: '9728543771',
      firstName: 'Michael',
      lastName: 'Richardson-Clarke',
      fullName: 'Mr Michael James Richardson-Clarke',
      middleNames: 'James',
      namePrefix: 'Mr',
      nameSuffix: '',
      address_line_1: 'Mr Michael James Richardson-Clarke',
      address_line_2: 'Apartment 42B The Granary Building',
      address_line_3: 'Wellington Place Business Park',
      address_line_4: 'Leeds',
      address_line_5: 'West Yorkshire',
      address_line_6: 'LS1 4AP',
      address_line_7: '',
    },
  },
  {
    id: 'long-2',
    name: 'Dr Elizabeth Anne Thompson',
    data: {
      nhsNumber: '9728543772',
      firstName: 'Elizabeth',
      lastName: 'Thompson',
      fullName: 'Dr Elizabeth Anne Thompson',
      middleNames: 'Anne',
      namePrefix: 'Dr',
      nameSuffix: '',
      address_line_1: 'Dr Elizabeth Anne Thompson',
      address_line_2: 'The Old Rectory Church Lane',
      address_line_3: 'Little Snoring-on-the-Wold',
      address_line_4: 'Gloucestershire',
      address_line_5: 'GL54 1AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-3',
    name: 'Dame Catherine Elizabeth Montgomery',
    data: {
      nhsNumber: '9728543773',
      firstName: 'Catherine',
      lastName: 'Montgomery',
      fullName: 'Dame Catherine Elizabeth Montgomery',
      middleNames: 'Elizabeth',
      namePrefix: 'Dame',
      nameSuffix: 'DBE',
      address_line_1: 'Dame Catherine E Montgomery DBE',
      address_line_2: 'Flat 15 Kensington Court Apartments',
      address_line_3: 'Kensington High Street',
      address_line_4: 'Royal Borough of Kensington and Chelsea',
      address_line_5: 'London',
      address_line_6: 'W8 5NP',
      address_line_7: '',
    },
  },
  {
    id: 'long-4',
    name: 'Mr Rajesh Kumar Chandrasekaran',
    data: {
      nhsNumber: '9728543774',
      firstName: 'Rajesh',
      lastName: 'Chandrasekaran',
      fullName: 'Mr Rajesh Kumar Chandrasekaran',
      middleNames: 'Kumar',
      namePrefix: 'Mr',
      nameSuffix: '',
      address_line_1: 'Mr Rajesh Kumar Chandrasekaran',
      address_line_2: '14 Victoria Gardens',
      address_line_3: 'Westbourne-on-Sea',
      address_line_4: 'East Sussex',
      address_line_5: 'BN11 1AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-5',
    name: 'Ms Aminatou Diallo Kouyaté',
    data: {
      nhsNumber: '9728543775',
      firstName: 'Aminatou',
      lastName: 'Diallo Kouyaté',
      fullName: 'Ms Aminatou Diallo Kouyaté',
      middleNames: '',
      namePrefix: 'Ms',
      nameSuffix: '',
      address_line_1: 'Ms Aminatou Diallo Kouyaté',
      address_line_2: '25 Riverside Tower',
      address_line_3: 'Victoria Embankment Gardens',
      address_line_4: 'City of Westminster',
      address_line_5: 'London',
      address_line_6: 'SW1A 2AA',
      address_line_7: '',
    },
  },
  {
    id: 'long-6',
    name: 'Sir William Alexander Fitzgerald',
    data: {
      nhsNumber: '9728543776',
      firstName: 'William',
      lastName: 'Fitzgerald',
      fullName: 'Sir William Alexander Fitzgerald',
      middleNames: 'Alexander',
      namePrefix: 'Sir',
      nameSuffix: 'KBE',
      address_line_1: 'Sir William Alexander Fitzgerald KBE',
      address_line_2: 'Harbour Masters Cottage',
      address_line_3: 'The Old Dockyard Portsmouth',
      address_line_4: 'Hampshire',
      address_line_5: 'PO1 3LJ',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-7',
    name: 'Dr Priya Sharma-Williamson',
    data: {
      nhsNumber: '9728543777',
      firstName: 'Priya',
      lastName: 'Sharma-Williamson',
      fullName: 'Dr Priya Sharma-Williamson',
      middleNames: '',
      namePrefix: 'Dr',
      nameSuffix: '',
      address_line_1: 'Dr Priya Sharma-Williamson',
      address_line_2: 'The Grange Willowbrook Lane',
      address_line_3: 'Upper Slaughter-on-Thames',
      address_line_4: 'Oxfordshire',
      address_line_5: 'OX18 4AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-8',
    name: 'Rev Emmanuel Kwabena Adomako',
    data: {
      nhsNumber: '9728543778',
      firstName: 'Emmanuel',
      lastName: 'Adomako',
      fullName: 'Rev Emmanuel Kwabena Adomako',
      middleNames: 'Kwabena',
      namePrefix: 'Rev',
      nameSuffix: '',
      address_line_1: 'Rev Emmanuel Kwabena Adomako',
      address_line_2: 'Thornfield Manor Estate Office',
      address_line_3: 'Cholmondeley Park Gardens',
      address_line_4: 'Cheshire',
      address_line_5: 'CW6 9AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-9',
    name: 'Prof Franziska Vogel-Bernhardt',
    data: {
      nhsNumber: '9728543779',
      firstName: 'Franziska',
      lastName: 'Vogel-Bernhardt',
      fullName: 'Prof Franziska Vogel-Bernhardt',
      middleNames: '',
      namePrefix: 'Prof',
      nameSuffix: '',
      address_line_1: 'Prof Franziska Vogel-Bernhardt',
      address_line_2: 'Institute of Advanced Studies',
      address_line_3: 'University Boulevard Newcastle',
      address_line_4: 'Tyne and Wear',
      address_line_5: 'NE1 7RU',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-10',
    name: "Mrs Margaret Anne O'Sullivan",
    data: {
      nhsNumber: '9728543780',
      firstName: 'Margaret',
      lastName: "O'Sullivan",
      fullName: "Mrs Margaret Anne O'Sullivan",
      middleNames: 'Anne',
      namePrefix: 'Mrs',
      nameSuffix: '',
      address_line_1: "Mrs Margaret Anne O'Sullivan",
      address_line_2: 'St Christophers Presbytery',
      address_line_3: 'Cathedral Close Salisbury',
      address_line_4: 'Wiltshire',
      address_line_5: 'SP1 2EF',
      address_line_6: '',
      address_line_7: '',
    },
  },
  {
    id: 'long-11',
    name: 'Dr Christopher James Harrington',
    data: {
      nhsNumber: '9728543781',
      firstName: 'Christopher',
      lastName: 'Harrington',
      fullName: 'Dr Christopher James Harrington',
      middleNames: 'James',
      namePrefix: 'Dr',
      nameSuffix: '',
      address_line_1: 'Dr Christopher James Harrington',
      address_line_2: 'Meadowbank Surgery Greenfields',
      address_line_3: 'Little Hampton-in-the-Vale',
      address_line_4: 'Northamptonshire',
      address_line_5: 'NN12 8AA',
      address_line_6: '',
      address_line_7: '',
    },
  },
];
