name: "TFSec Scan"
description: "Scan HCL using TFSec"
runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v3
    - uses: asdf-vm/actions/setup@v3
    - name: "TFSec Scan - Components"
      shell: bash
      run: |
        components_exit_code=0
        modules_exit_code=0

        ./scripts/terraform/tfsec.sh ./infrastructure/terraform/components || components_exit_code=$?
        ./scripts/terraform/tfsec.sh ./infrastructure/terraform/module || modules_exit_code=$?

        if [ $components_exit_code -ne 0 ] || [ $modules_exit_code -ne 0 ]; then
          echo "One or more TFSec scans failed."
          exit 1
        fi
