name: "Normalize branch name"
description: "Normalize branch name"
outputs:
  normalized_branch_name:
    value: ${{ steps.normalize_branch_name.outputs.normalized_branch_name }}
runs:
  using: "composite"
  steps:
    - id: normalize_branch_name
      shell: bash
      run: echo "normalized_branch_name=$(sed -e 's/[^a-zA-Z0-9-]//g' <<< $(git rev-parse --abbrev-ref HEAD) | tr '[:upper:]' '[:lower:]' | head -c 25)" >> $GITHUB_OUTPUT

