name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true

  targetEnvironment:
    description: Name of the environment under test
    required: true

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-template-management-dev
    required: true

  targetComponent:
    description: Name of the component under test
    required: true

runs:
  using: "composite"

  steps:
    - name: Fetch terraform output
      uses: actions/download-artifact@v4
      with:
        name: terraform-output-${{ inputs.targetComponent }}
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci

    - name: Generate outputs file
      shell: bash
      run: |
        root_dir=${GITHUB_WORKSPACE}
        mv ./terraform_output.json ./sandbox_tf_outputs.json
        npm run generate-outputs sandbox-output

    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        make test-${{ inputs.testType }}

    - name: Archive ui-e2e test results
      if: ${{ inputs.testType == 'ui-e2e' }}
      uses: actions/upload-artifact@v4
      with:
        name: UI E2E test report
        path: "tests/test-team/playwright-report"

    - name: Archive ui-component test results
      if: ${{ inputs.testType == 'ui-component' }}
      uses: actions/upload-artifact@v4
      with:
        name: UI-component test report
        path: "tests/test-team/playwright-report"

    - name: Archive api test results
      if: ${{ inputs.testType == 'api' }}
      uses: actions/upload-artifact@v4
      with:
        name: API test report
        path: "tests/test-team/playwright-report"

    - name: Archive accessibility results
      if: ${{ inputs.testType == 'accessibility' }}
      uses: actions/upload-artifact@v4
      with:
        name: accessibility
        path: "tests/accessibility/.reports/accessibility"
