name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true

  targetEnvironment:
    description: Name of the environment under test
    required: true

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-template-management-dev
    required: true

  targetComponent:
    description: Name of the component under test
    required: true

runs:
  using: "composite"

  strategy:
  fail-fast: false
  matrix:
    shardIndex: [1, 2, 3, 4]
    shardTotal: [4]

  steps:
    - name: Fetch terraform output
      uses: actions/download-artifact@v5
      with:
        name: terraform-output-${{ inputs.targetComponent }}
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Generate outputs file
      shell: bash
      run: |
        root_dir=${GITHUB_WORKSPACE}
        mv ./terraform_output.json ./sandbox_tf_outputs.json
        npm run generate-outputs sandbox-output

    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        npx playwright test --project=component:setup
        npx playwright test --project=component --no-deps --shard${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        npx playwright test --project=component:teardown --no-deps


    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ inputs.testType }} - test report
        path: "tests/acceptance-test-report"
