#!/bin/bash
set -euo pipefail

# Uploads Pact contract files generated by running consumer Pact tests
# These files should be downloaded by the provider for use in provider tests

script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

consumer_service_dirs=("auth" "core")
consumer_pact_dir="consumer/pacts"

for consumer in "${consumer_service_dirs[@]}"; do
  source="${script_path}/../tests/${consumer}/${consumer_pact_dir}"

  if [ -d "${source}" ]; then
    source_dir=$(realpath "${source}")

    echo "Looking for pact files in $source_dir..."

    for file in "$source_dir"/*.json; do
      if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        provider=$(cat $file | jq -r ".provider.name")

        targetPath="pacts/$provider/$filename"

        aws s3 cp "$file" "s3://$PACT_BUCKET/$targetPath"
      fi
    done
  fi
done

echo "All Pact files uploaded successfully."
