import {
  S3Client,
  ListObjectsV2Command,
  GetObjectCommand,
} from '@aws-sdk/client-s3';
import { Readable } from 'node:stream';

async function streamToString(stream: Readable): Promise<string> {
  return await new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    stream.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    stream.on('error', (err) => reject(err));
    stream.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
  });
}

export class EmailHelper {
  private readonly s3Client = new S3Client({ region: 'eu-west-2' });

  private readonly testEmailBucketName = process.env.TEST_EMAIL_BUCKET_NAME;

  constructor() {}

  async getAllS3Items(prefix: string) {
    const { Contents = [], ContinuationToken } = await this.s3Client.send(
      new ListObjectsV2Command({
        Bucket: this.testEmailBucketName,
        Prefix: prefix,
      })
    );

    let nextToken = ContinuationToken;
    let s3Items = Contents;

    while (nextToken) {
      const {
        Contents: newContents = [],
        ContinuationToken: newContinuationToken,
      } = await this.s3Client.send(
        new ListObjectsV2Command({
          Bucket: this.testEmailBucketName,
          Prefix: prefix,
          ContinuationToken: nextToken,
        })
      );

      s3Items = [...s3Items, ...newContents];
      nextToken = newContinuationToken;
    }

    return s3Items;
  }

  async getEmailForTemplateId(
    prefix: string,
    templateId: string,
    dateCutoff: Date
  ) {
    const s3Items = await this.getAllS3Items(prefix);

    const sortedKeys = s3Items
      .filter(({ LastModified }) => (LastModified ?? 0) > dateCutoff)
      .sort(
        (a, b) =>
          (b.LastModified?.getTime() ?? 0) - (a.LastModified?.getTime() ?? 0)
      );

    // SES does not tell us what the S3 keys are going to be for received emails,
    // so we have to search all recent ones to ensure we get the right one and
    // not one that was generated by a different test
    for (const { Key } of sortedKeys) {
      const getCommand = new GetObjectCommand({
        Bucket: this.testEmailBucketName,
        Key,
      });

      const { Body } = await this.s3Client.send(getCommand);

      if (!Body || !(Body instanceof Readable)) {
        throw new Error('Unexpected response body type');
      }

      const content = await streamToString(Body);

      if (content.includes(templateId)) {
        return content;
      }
    }

    throw new Error('Email not found');
  }
}
