export const ErrorCodes = {
  MESSAGE_CONTAINS_INVALID_PERSONALISATION_FIELD_NAME:
    'MESSAGE_CONTAINS_INVALID_PERSONALISATION_FIELD_NAME',
  TEMPLATE_IN_USE: 'TEMPLATE_IN_USE',
  INITIAL_RENDER_CONTAINS_TOO_MANY_SHEETS:
    'INITIAL_RENDER_CONTAINS_TOO_MANY_SHEETS',
  SHORT_RENDER_CONTAINS_TOO_MANY_SHEETS:
    'SHORT_RENDER_CONTAINS_TOO_MANY_SHEETS',
  LONG_RENDER_CONTAINS_TOO_MANY_SHEETS: 'LONG_RENDER_CONTAINS_TOO_MANY_SHEETS',
} as const;
