name: Post-deployment tests

on:
  workflow_call:
    inputs:
      targetEnvironment:
        description: Name of the static environment under test
        required: true
        default: main
        type: string

      targetAccountGroup:
        description: Name of the Account Group under test
        default: nhs-notify-template-management-dev
        required: true
        type: choice
        options:
          - nhs-notify-template-management-dev
          - nhs-notify-template-management-nonprod
          - nhs-notify-template-management-prod

      targetComponent:
        description: Name of the Component under test
        default: app
        type: choice
        options:
          - acct
          - app
          - branch

concurrency:
  group: ${{ github.workflow }}-${{ inputs.targetComponent }}-${{ inputs.targetEnvironment }}-${{ inputs.targetAccountGroup }}
  cancel-in-progress: false

jobs:
  post-deploy:
    name: Log post-deployment details
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch terraform output
        uses: actions/download-artifact@v4
        with:
          name: terraform-output-${{ inputs.targetComponent }}

      - name: Extract configuration details
        run: |
          # Extract config from terraform outputs
          ls
          cat terraform_output.json | jq
          echo APP=$(cat terraform_output.json | jq -r .amplify.value.id) >> $GITHUB_ENV
          echo DOMAIN=$(cat terraform_output.json | jq -r .amplify.value.domain_name) >> $GITHUB_ENV
          echo AWS_REGION=$(cat terraform_output.json | jq -r .deployment.value.aws_region) >> $GITHUB_ENV
          echo AWS_ACCOUNT_ID=$(cat terraform_output.json | jq -r .deployment.value.aws_account_id) >> $GITHUB_ENV

      - name: Check configuration
        run: |
          if [[ "DOMAIN" == "null" ]]; then
            echo "::warning::Deployment output not available to trigger post-deployment workflow."
            exit 1
          fi

      - name: Post-deployment
        run: |
          echo "Post deployment workflow for $DOMAIN"
          pwd
          ls -la
