
name: PR Create Environment

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, unlabeled, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-dynamic-environment:
    name: Create Dynamic Environment
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable_internal_repo_build.yaml
    secrets: inherit
    with:
      jobName: Sandbox set up
      infraRepoName: nhs-notify-web-template-management
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-deploy-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-template-management-dev
      targetComponent: branch
      terraformAction: apply
      overrides: branch_name=${{ github.head_ref || github.ref_name }}
