
name: PR Create Environment

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, unlabeled, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-dynamic-environment:
    name: Create Dynamic Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Trigger dynamic environment creation
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        shell: bash
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Create PR Dynamic Environment" \
            --infraRepoName "$(echo ${{ github.repository }} | cut -d'/' -f2)" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetComponent "branch" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --terraformAction "apply"

  create-sandbox-environment:
    name: Create Sandbox Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Trigger sandbox environment creation
        shell: bash
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Create PR Sandbox " \
            --infraRepoName "nhs-notify-web-template-management" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --targetComponent "sandbox" \
            --terraformAction "apply"

