
name: PR Create Environment

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, unlabeled, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-dynamic-environment:
    name: Create Dynamic Environment
    runs-on: ubuntu-latest

    steps:
      - name: Trigger nhs-notify-internal dynamic environment workflow
        needs: generate-sandbox-name
        uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
        with:
          jobName: Sandbox set up
          infraRepoName: nhs-notify-web-template-management
          releaseVersion: ${{ github.head_ref || github.ref_name }}
          targetWorkflow: dispatch-deploy-dynamic-env.yaml
          targetEnvironment: pr${{ github.event.number }}
          targetAccountGroup: nhs-notify-template-management-dev
          targetComponent: branch
          terraformAction: apply
          overrides: branch_name=${{ github.head_ref || github.ref_name }}
