name: PR Merged

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-merge:
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.check.outputs.merged }}
    steps:
      - name: Check if PR was merged
        id: check
        run: echo "merged=${{ github.event.pull_request.merged }}" >> $GITHUB_ENV

  deploy-main:
    needs: check-merge
    if: needs.check-merge.outputs.merged == 'true'
    name: Deploy changes to main in dev AWS account

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, app]

    uses: ./.github/workflows/reusable_internal_repo_build.yaml
    secrets: inherit
    with:
      releaseVersion: main
      targetWorkflow: "dispatch-deploy-static-notify-web-template-management-env.yaml"
      targetEnvironment: "main"
      targetAccountGroup: "nhs-notify-template-management-dev"
      targetComponent: ${{ matrix.component }}
      terraformAction: "apply"
