name: Github Release Created

on:
  release:
    types: ["published"] # Inherits all input defaults

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main in nonprod AWS Account
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, app]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Nonprod Environment
        env:
            PEM_FILE: ${{ secrets.GITHUB_APP_PEM_FILE }}
            CLIENT_ID: ${{ secrets.GITHUB_APP_CLIENT_ID }}
        run: |
          bash .github/scripts/dispatch_internal_repo_workflow.sh \
            --releaseVersion "${{ github.event.release.tag_name }}" \
            --targetWorkflow "dispatch-deploy-static-notify-web-template-management-env.yaml" \
            --targetEnvironment "main" \
            --targetAccountGroup "nhs-notify-template-management-nonprod" \
            --targetComponent "${{ matrix.component }}" \
            --terraformAction "apply"
