name: Github Release Created

on:
  release:
    types: ["published"] # Inherits all input defaults

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-main:
    name: Deploy changes to main in nonprod AWS Account

    permissions:
      id-token: write
      contents: read

    strategy:
      max-parallel: 1
      matrix:
        component: [acct, app]

    uses: ./.github/workflows/reusable/internal_repo_build.yaml
    secrets: inherit
    with:
      release_version: ${{ github.event.release.tag_name }}
      target_workflow: "dispatch-deploy-static-notify-web-template-management-env.yaml"
      tf_environment: "main"
      tf_group: "nhs-notify-template-management-nonprod"
      tf_component: ${{ matrix.component }}
      tf_action: "apply"
