name: Call Notify Internal Infrastructure Deployment
## Sub workflow which plans and deploys Notify components as part of the workflow.
## Review Gates may be required to proceed on triggered builds.

on:
  workflow_call:
    inputs:
      releaseVersion:
        type: string
        description: The Github release version, commit, or tag.
        default: main
      targetWorkflow:
        type: string
        description: The name of the github workflow to call.
        default: main
      targetEnvironment:
        type: string
        description: The Terraform environment to deploy
        default: main
      targetComponent:
        type: string
        description: The Terraform component to deploy
        required: true
      targetAccountGroup:
        type: string
        description: The Terraform group to deploy
        required: true
      terraformAction:
        type: string
        description: The Terraform component to deploy
        default: plan

concurrency:
  group: ${{ inputs.targetEnvironment }}-${{ inputs.targetAccountGroup }}-${{ inputs.targetComponent }}-${{ inputs.terraformAction }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Trigger nhs-notify-internal static environment workflow deployment
        shell: bash
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Static environment workflow deployment" \
            --releaseVersion "${{ inputs.releaseVersion }}" \
            --targetWorkflow "${{ inputs.targetWorkflow }}" \
            --targetEnvironment "${{ inputs.targetEnvironment }}" \
            --targetAccountGroup "${{ inputs.targetAccountGroup }}" \
            --targetComponent "${{ inputs.targetComponent }}" \
            --terraformAction "${{ inputs.terraformAction }}"
