name: "Acceptance stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  environment-set-up:
    name: "Environment set up"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Repo setup"
        run: |
          npm ci
      - name: "Create sandbox"
        run: |
          ./scripts/create_sandbox.sh
      - uses: actions/upload-artifact@v4
        with:
          name: amplify_outputs.json
          path: amplify_outputs.json
  test-security:
    name: "Security test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Run security test"
        run: |
          make test-security
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-ui:
    name: "UI test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Run UI test"
        run: |
          make test-ui
      - name: "Save result"
        run: |
          echo "Nothing to save"
  test-accessibility:
    name: "Accessibility test"
    runs-on: ubuntu-latest
    needs: environment-set-up
    timeout-minutes: 10
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: amplify_outputs.json
      - name: "Repo setup"
        run: |
          npm ci
      - name: "Run accessibility test"
        run: make test-accessibility
      - name: Archive accessibility results
        uses: actions/upload-artifact@v4
        with:
          name: accessibility
          path: ".reports/accessibility"
  environment-tear-down:
    name: "Environment tear down"
    runs-on: ubuntu-latest
    needs: test-accessibility
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Destroy sandbox"
        run: |
          npm run destroy-sandbox
