name: Acceptance stage

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  acceptance-tests:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Acceptance Tests
        shell: bash
        env:
          PR_TRIGGER_PAT: ${{ secrets.PR_TRIGGER_PAT }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --jobName "Acceptance tests" \
            --infraRepoName "nhs-notify-web-template-management" \
            --releaseVersion "${{ github.head_ref || github.ref_name }}" \
            --targetWorkflow "dispatch-contextual-tests-dynamic-env.yaml" \
            --targetEnvironment "${{ needs.generate-sandbox-name.outputs.SANDBOX_NAME }}" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --targetComponent "sandbox"