name: Acceptance stage

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  log-event:
    name: Log event
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Log event"
        run: |
          echo number${{ github.event.number }}
          echo action${{ github.event.action }}
          echo pull_request${{ github.event.pull_request }}
          echo push${{ github.event.push }}
          echo issue${{ github.event.issue }}
          echo workflow${{ github.workflow }}
          echo ref${{ github.ref }}
          echo repository${{ github.repository }}
          echo id${{ github.event.id }}
          echo event${{ github.event }}
          echo github${{ github }}
          echo event${{ toJson(github.event) }}
          echo github${{ toJson(github) }}

  sandbox-set-up:
    name: Step 1
    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Sandbox set up
      infraRepoName: nhs-notify-web-template-management
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-deploy-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-template-management-dev
      targetComponent: sandbox
      terraformAction: apply

  acceptance-tests:
    name: Step 2
    needs: sandbox-set-up

    # Calls out to the nhs-notify-internal repo.
    # The nhs-notify-internal repo will run the tests
    # setup in ./.github/actions/acceptance-tests/action.yaml
    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Acceptance tests
      infraRepoName: nhs-notify-web-template-management
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-acceptance-tests-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-template-management-dev
      targetComponent: sandbox

  sandbox-tear-down:
    name: Step 3
    needs: acceptance-tests
    if: always()

    uses: ./.github/workflows/dispatch_internal_repo_workflow.yaml
    secrets: inherit
    with:
      jobName: Sandbox tear down
      infraRepoName: nhs-notify-web-template-management
      releaseVersion: ${{ github.head_ref || github.ref_name }}
      targetWorkflow: dispatch-deploy-dynamic-env.yaml
      targetEnvironment: pr${{ github.event.number }}
      targetAccountGroup: nhs-notify-template-management-dev
      targetComponent: sandbox
      terraformAction: destroy
