name: Acceptance stage

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string


permissions:
  id-token: write
  contents: read

jobs:
  run-acceptance-tests:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0

      - name: Trigger Sandbox Environment Build
        shell: bash
        env:
          PEM_FILE: ${{ secrets.GITHUB_APP_PEM_FILE }}
          CLIENT_ID: ${{ secrets.GITHUB_APP_CLIENT_ID }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --infraRepoName "nhs-notify-web-template-management" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ inputs.pr_number }}" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --targetComponent "sandbox" \
            --terraformAction "apply"

      - name: Trigger Acceptance Tests
        shell: bash
        env:
          PEM_FILE: ${{ secrets.GITHUB_APP_PEM_FILE }}
          CLIENT_ID: ${{ secrets.GITHUB_APP_CLIENT_ID }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --infraRepoName "nhs-notify-web-template-management" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-contextual-tests-dynamic-env.yaml" \
            --targetEnvironment "pr${{ inputs.pr_number }}" \
            --targetAccountGroup "nhs-notify-template-management-dev" \
            --targetComponent "sandbox"
